w

diff --git a/siteconfig/job-downgrade-replacement-flow.yaml b/siteconfig/job-downgrade-replacement-flow.yaml
--- a/siteconfig/job-downgrade-replacement-flow.yaml
+++ b/siteconfig/job-downgrade-replacement-flow.yaml
@@ -1,7 +1,7 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: job-execute-backup
+  name: job-downgrade-replacement-flow
   annotations:
     argocd.argoproj.io/sync-wave: "3"
 spec:
@@ -21,33 +21,43 @@ spec:
                     echo -e "[`date '+%m-%d-%Y %H:%M:%S'`] $txt" 
                 }
          
-                function create_managed_view() {
+                function create_managed_view_backup() {
                    cr=$1
-                   echo -e "apiVersion: view.open-cluster-management.io/v1beta1\nkind: ManagedClusterView\nmetadata:\n   name: backup-${cr}-view\n   namespace: ${cr}\nspec:\n   scope:\n      apiGroup: velero.io\n      kind: Backup\n      name: backup-${NEWNAME}-1\n      namespace: openshift-adp\n      resource: backups.velero.io" | oc apply -f -
+                   echo -e "apiVersion: view.open-cluster-management.io/v1beta1\nkind: ManagedClusterView\nmetadata:\n   name: backup-${cr}-view\n   namespace: ${cr}\nspec:\n   scope:\n      apiGroup: velero.io\n      kind: Backup\n      name: backup-${NEWNAME}\n      namespace: openshift-adp\n      resource: backups.velero.io" | oc apply -f -
                 }
 
-                function create_managed_action() {
+                function create_managed_action_backup() {
                    cr=$1
-                   echo -e "apiVersion: action.open-cluster-management.io/v1beta1\nkind: ManagedClusterAction\nmetadata:\n   name: ${cr}-backup-workload-1\n   namespace: ${cr}\nspec:\n  actionType: Create\n  kube:\n    resources: backups.velero.io\n    name: backup-${NEWNAME}-1\n    template:\n        apiVersion: velero.io/v1\n        kind: Backup\n        metadata:\n          labels:\n             velero.io/storage-location: example-dpa-1\n          name: backup-${NEWNAME}-1\n          namespace: openshift-adp\n        spec:\n          defaultVolumestoRestic: false\n          hooks: {}\n          includedNamespaces:\n          - workload\n          metadata: {}\n          storageLocation: example-dpa-1" | oc apply -f -
+                   echo -e "apiVersion: action.open-cluster-management.io/v1beta1\nkind: ManagedClusterAction\nmetadata:\n   name: backup-${cr}-workload\n   namespace: ${cr}\nspec:\n  actionType: Create\n  kube:\n    resources: backups.velero.io\n    name: backup-${NEWNAME}\n    template:\n        apiVersion: velero.io/v1\n        kind: Backup\n        metadata:\n          labels:\n             velero.io/storage-location: example-dpa-1\n          name: backup-${NEWNAME}\n          namespace: openshift-adp\n        spec:\n          defaultVolumestoRestic: false\n          hooks: {}\n          includedNamespaces:\n          - workload\n          metadata: {}\n          storageLocation: example-dpa-1" | oc apply -f -
                 }
 
+                function create_managed_action_restore() {
+                   cr=$1
+                   echo -e "apiVersion: action.open-cluster-management.io/v1beta1\nkind: ManagerClusterAction\nmetadata:\n   name: restore-${cr}-workload\n   namespace: ${cr}\nspec:\n   actionType: Create\n   kube:\n      resource: restores.velero.io\n      name: restore-${NEWNAME}\n      template:\n        apiVersion: velero.io/v1\n        kind: Restore\n        metadata:\n           name: restore-${NEWNAME}\n           namespace: openshift-adp\n        spec:\n           backupName: backup-${NEWNAME}\n           excludedResources:\n           - nodes\n           - events\n           - events.events.k8s.io\n           - backups.velero.io\n           - restores.velero.io\n           - resticrepositories.velero.io\n           includedNamespaces:\n           - workload" | oc apply -f -
+                }
  
+                function create_managed_view_restore() {
+                   cr=$1
+                   echo -e "apiVersion: view.open-cluster-management.io/v1beta1\nkind: ManagedClusterView\nmetadata:\n   name: restore-${cr}-view\n   namespace: ${cr}\nspec:\n   scope:\n      apiGroup: velero.io\n      kind: Restore\n      name: restore-${NEWNAME}\n      namespace: openshift-adp\n      resource: restores.velero.io" | oc apply -f -
+                }
+
                 logc "START Backup"
                 logc "============================="
                 CLUSTER_BACKUP_START_TIME=`date +%s`
    
-                NS=`oc get sa -o=jsonpath='{.items[0]..metadata.namespace}'`
+                NS=`oc get sa -o jsonpath='{.items[0]..metadata.namespace}'`
                 PRE=`date +%Y-%m-%d-%H-%M`
                 NEWNAME=$NS-$PRE
         
                 logc "Create ManagedClusterAction Backup for $NS"
-                create_managed_action $NS
+                create_managed_action_backup $NS
                 logc "Create ManagedClusterView for Backup"
-                create_managed_view $NS
+                create_managed_view_backup $NS
                        
                 logc "Monitor backup status"
 
                 ct=0
+                BKP_CHECK=0
                 while [[ $ct -le 20 ]]; do
                    BKP_STATUS=`oc get managedclusterview backup-${NS}-view -n ${NS} -o jsonpath='{.status.result.status.phase}'`
 
@@ -55,6 +65,7 @@ spec:
                       logc "Backup failed:"
                       oc get managedclusterview backup-${NS}-view -n ${NS} -o jsonpath='{.status.result.status}'
                       echo
+                      BKP_CHECK=1
                       break
                    elif [[ "$BKP_STATUS" == "Completed" ]]; then
                       logc "Backup successfully completed: "
@@ -73,11 +84,25 @@ spec:
                    ct=$(($ct+1))
                 done
                 
+                CLUSTER_BACKUP_END_TIME=`date +%s`
+
+                if [[ $BKP_CHECK -eq 1 ]]; then
+                   logc "Backup failed, interrupt process"
+                   logc "Notify failure" 
+
+                   CLUSTER_TOTAL_TIME=`echo $(( $CLUSTER_BACKUP_START_TIME - $CLUSTER_BACKUP_END_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`
+                   RESP_START_TIME=`date -d @$CLUSTER_BACKUP_START_TIME '+%m-%d-%Y %H:%M:%S'`
+                   RESP_END_TIME=`date -d @CLUSTER_BACKUP_END_TIME '+%m-%d-%Y %H:%M:%S'`
+
+                   curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$CLUSTER_TOTAL_TIME\", \"state\": \"FAILED\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
+                   exit 1                  
+                fi
+
+
                 # delete managedcluster
                 # delete clusterdeployment
                 # delete infraenv
                 # delete bmh
-
                 logc "Trigger cluster reprovisioning by deleting ClusterDeployment, InfraEnv and BMH"
 
                 logc "Current ManagedCluster: "
@@ -97,14 +122,10 @@ spec:
 
                 logc "Current BMH: "
                 oc get bmh -n $NS
-                # patch BMH remove current image and set metadata
-                # TODO
                 logc "Delete BMH: "
                 oc get bmh -n $NS | grep -v NAME | awk '{print $1}' | xargs oc delete bmh -n $NS
               
                 
-           
-
                 # monitor new cluster install
                 ct=0
                 INSTALL_STATUS=0
@@ -269,33 +290,100 @@ spec:
                     ct=$(($ct+1))
                   done
                   
-                  logc "Summary Deployment"
-                  logc "======================"
-                  logc "Cluster install start time: `date -d @$CLUSTER_START_TIME '+%m-%d-%Y %H:%M:%S'`"
-                  logc "Cluster install stop time: `date -d @$CLUSTER_END_TIME '+%m-%d-%Y %H:%M:%S'`"
-                  logc "Cluster install total time: $CLUSTER_TOTAL_TIME\n"
-                  logc "Policies deployment start time: `date -d @$POLICY_START_TIME '+%m-%d-%Y %H:%M:%S'`"
-                  logc "Policies deployment stop time: `date -d @$POLICY_END_TIME '+%m-%d-%Y %H:%M:%S'`"
-    
-    
                   POLICY_TOTAL_TIME=`echo $(( $POLICY_END_TIME - $POLICY_START_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`
-                                
-                  logc "Policy deployment total time: $POLICY_TOTAL_TIME\n"
+                  
     
                   TOTAL_TIME=`echo $(( $POLICY_END_TIME - $CLUSTER_START_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`
     
   
                   # cluster installation completed
-                  
-                  logc "Notify cluster $NS deployment is completed"
+                  logc "Cluster $NS deployment is completed"
                   RESP_START_TIME=`date -d @${CLUSTER_START_TIME} '+%m-%d-%Y %H:%M:%S'`
                   RESP_END_TIME=`date -d @${POLICY_END_TIME} '+%m-%d-%Y %H:%M:%S'`
-                  #curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"CREATE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$TOTAL_TIME\", \"state\": \"SUCCESS\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
-
    
                   # Trigger cluster restore procedure
-                  # TODO
+                  logc "Restore backup from OADP.."
+                  logc "Create ManagedClusterAction Restore for $NS"
+                  create_managed_action_restore $NS
+                  logc "Create ManagedClusterView for backup restore"
+                  create_managed_view_restore $NS
 
+                  # monitor backup restore
+                  ct=0
+                  REC_CHECK=0
+                  CLUSTER_RESTORE_START_TIME=`date +%s`
+                  while [[ $ct -le 20 ]]; do
+                   REC_STATUS=`oc get managedclusterview restore-${NS}-view -n ${NS} -o jsonpath='{.status.result.status.phase}'`
+
+                   if [[ "$REC_STATUS" == "Failed" ]]; then
+                      logc "Restore backup failed:"
+                      oc get managedclusterview restore-${NS}-view -n ${NS} -o jsonpath='{.status.result.status}'
+                      echo
+                      RES_CHECK=1
+                      break
+                   elif [[ "$RES_STATUS" == "Completed" ]]; then
+                      logc "Backup successfully completed: "
+                      oc get managedclusterview restore-${NS}-view -n ${NS} -o jsonpath='{.status.result.status}'
+                      echo
+                      break
+                   elif [[ "$RES_STATUS" == "InProgress" ]]; then
+                      logc "Backup is in progress..."
+                   else
+                      logc "Backup status unknown: "
+                      oc get managedclusterview restore-${NS}-view -n ${NS} -o jsonpath='{.status.result.status}'
+                      echo
+                   fi
+
+                   sleep 10
+                   ct=$(($ct+1))
+                  done
+                  
+                  if [[ $RES_CHECK -eq 1 ]]; then
+                   logc "Backup restore failed, interrupt process"
+                   logc "Notify failure"
+
+                   CLUSTER_TOTAL_TIME=`echo $(( $CLUSTER_RESTORE_START_TIME - $CLUSTER_RESTORE_END_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`
+                   RESP_START_TIME=`date -d @$CLUSTER_RESTORE_START_TIME '+%m-%d-%Y %H:%M:%S'`
+                   RESP_END_TIME=`date -d @CLUSTER_RESTORE_END_TIME '+%m-%d-%Y %H:%M:%S'`
+
+                   echo "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$CLUSTER_TOTAL_TIME\", \"state\": \"FAILED\", \"reason\": \"\"}"
+
+                   curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$CLUSTER_TOTAL_TIME\", \"state\": \"FAILED\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
+                   exit 1                
+
+                  fi
+                  
+
+
+                  CLUSTER_RESTORE_END_TIME=`date +%s`
+                  
+                  CLUSTER_BACKUP_TOTAL_TIME=`echo $(( $CLUSTER_BACKUP_END_TIME - $CLUSTER_BACKUP_START_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`  `date -d @$CLUSTER_BACKUP_START_TIME '+%m-%d-%Y %H:%M:%S'`
+                  CLUSTER_RESTORE_TOTAL_TIME=`echo $(( $CLUSTER_RESTORE_END_TIME - $CLUSTER_RESTORE_START_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`  `date -d @$CLUSTER_RESTORE_START_TIME '+%m-%d-%Y %H:%M:%S'`
+                  CLUSTER_TOTAL_TIME=`echo $(( $CLUSTER_RESTORE_END_TIME - $CLUSTER_BACKUP_START_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`  `date -d @$CLUSTER_BACKUP_START_TIME '+%m-%d-%Y %H:%M:%S'`
+
+                  logc "Summary"
+                  logc "======================"
+                  logc "Backup install start time: `date -d @$CLUSTER_BACKUP_START_TIME '+%m-%d-%Y %H:%M:%S'`" 
+                  logc "Backup install end time: `date -d @$CLUSTER_BACKUP_END_TIME '+%m-%d-%Y %H:%M:%S'`" 
+                  logc "Backup duration: $CLUSTER_BACKUP_TOTAL_TIME"     
+                  logc "Cluster install start time: `date -d @$CLUSTER_START_TIME '+%m-%d-%Y %H:%M:%S'`"
+                  logc "Cluster install end time: `date -d @$CLUSTER_END_TIME '+%m-%d-%Y %H:%M:%S'`"
+                  logc "Cluster install total time: $CLUSTER_TOTAL_TIME\n"
+                  logc "Policies deployment start time: `date -d @$POLICY_START_TIME '+%m-%d-%Y %H:%M:%S'`"
+                  logc "Policies deployment end time: `date -d @$POLICY_END_TIME '+%m-%d-%Y %H:%M:%S'`"              
+                  logc "Policies deployment total time: $POLICY_TOTAL_TIME\n"
+                  logc "Restore backup start time: `date -d @$CLUSTER_RESTORE_START_TIME '+%m-%d-%Y %H:%M:%S'`"
+                  logc "Restore backup end time: `date -d @$CLUSTER_RESTORE_START_TIME '+%m-%d-%Y %H:%M:%S'`"
+                  logc "Restore backup total time: $CLUSTER_RESTORE_TOTAL_TIME\n"
+        
+                  logc "Total flow duration: $CLUSTER_TOTAL_TIME\n"
+
+
+                  logc "Notify DOWNGRADE_CLUSTER_REPLY"
+                  echo "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$TOTAL_TIME\", \"state\": \"SUCCESS\", \"reason\": \"\"}"
+
+                  # notify cluster downgrad completed
+                  curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$TOTAL_TIME\", \"state\": \"SUCCESS\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
 
                   exit 0
                 else
@@ -306,15 +394,17 @@ spec:
                   logc "Send notification cluster $NS installation failed"
 
                   RESP_START_TIME=`date -d @${CLUSTER_START_TIME} '+%m-%d-%Y %H:%M:%S'`
-                  RESP_END_TIME=`date +'%m-%d-%Y %H:%M:%S'`
+                  RESP_END_TIME=`date +%s`
+                  DURATION=`echo $(( $CLUSTER_BACKUP_START_TIME - $RESP_END_TIME )) | awk '{printf "%d:%02d:%02d", $1/3600, ($1/60)%60, $1%60}'`  `date -d @$CLUSTER_BACKUP_START_TIME '+%m-%d-%Y %H:%M:%S'`
 
-                  curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"CREATE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"state\": \"FAILED\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
+                  echo "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$DURATION\", \"state\": \"FAILED\", \"reason\": \"\"}"
+
+                  curl -v -X POST -H 'Content-Type: application/json' -d "{\"type\": \"DOWNGRADE_CLUSTER_REPLY\", \"cluster_name\": \"$NS\", \"start_time\": \"$RESP_START_TIME\", \"end_time\": \"$RESP_END_TIME\", \"duration\": \"$DURATION\", \"state\": \"FAILED\", \"reason\": \"\"}" http://ztpintegration-amq.apps.ztphub.fedge.lab.com/ztp
                   exit 1
                 fi
 
-
         
                 EOF
-        name: execute-backup
+        name: downgrade-replacement-flow
         image: registry.redhat.io/openshift4/ose-cli
       restartPolicy: Never
